server:
  port: 8848

spring:
  application:
    name: transaction-mq-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/transaction_mq?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 1234
  redis:
    host: 10.10.18.145
    port: 6379
    password: cloud@ininin


mybatis:
  mapper-locations: classpath:com/in/g/mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:com/in/g/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true